### ISSUE TITLE
Underground lakes abruptly end at chunk boundaries 

### ISSUE THREAD

**Issue by superfluke** [kreezxil/Subterranean-Waters#2]
subh2o-1.12.2-1.5.6.jar
Forge 14.23.5.2768

Seems like quite a few of the underground lakes end as totally flat wall right at chunk boundaries. Based on how the other sides of the lake end more naturally, I assume this is a bug. Default config settings and cave generation turned off. 

![2019-04-17_13 16 01](https://user-images.githubusercontent.com/20022336/56314280-a0703000-6122-11e9-9530-86a87b33959e.png)

**Comment by kreezxil** [comment]
what do you mean by default cave generation turned off?

**Comment by superfluke** [comment]
Meant that as two separate things. I was using the subterranean default configs. Also I was working on a cave mod so I turned off all cave generation to see how the underground lakes generated alone. So, everything in the screenshot was generated by this mod.

**Comment by Tangosucka** [comment]
this happens still with latest build

**Comment by kreezxil** [comment]
the latest build only incorporated new default config options. if you can
solve the code issue for chunk boundaries, please feel free to do so and
submit a pull request.

**Comment by cvelde** [comment]
Most of the Chunk issues are solved by removing the biome check code (or config entries) since the check entirely blocks the chunk from being processed thus creating hard chunk borders. (This is very apparent for Rivers)

If the chance option were actually working it would also do that, albeit probably worse since random chunks would be missing.

There appear to be some glitches left after removing both but the code for the generator is not understandable, atleast to me.

**Comment by cvelde** [comment]
I also played around with replacing the entire generator to achieve a similar effect - although it seems quite pointless to push since basically the entire mod is ripped out and replaced.

**Comment by kreezxil** [comment]
those biome checks were put there to stop air bubbles in water biomes. Did you have a solution for that, and nothing wrong with having a complete mod rewrite. Do it, push the PR and I will not only publish that, but if you give me your CurseForge handle I'll cut you in for some of the CursePoints. 

https://authors.curseforge.com/store for more on that.

**Comment by cvelde** [comment]
I'm aware why you put them in, though probably the resulting chunk borders are worse than the actual problem. The solution would be to limit the height in those biomes in a gradual way, which is probably not that easy to do if at all possible since you can't know of the chunks around really.

If I did a complete rewrite I would probably put in some other features I personally would like and just make a new mod, thanks for the offer, but if it were to happen (I don't have the time frankly) and if I wanted to release it publicly it would be as a new mod since the goal and features would differ quite a bit from this.

**Comment by kreezxil** [comment]
@cvelde both this mod and the mod we branched from are MIT or similarily licensed. Feel free to fork or make a new mod entirely. If code is reused simply make the appropriate link back to satisfy the License.

You have my blessing for a new derivative of this mod, and if not, I look forward to your mod.

**Comment by kreezxil** [comment]
We're still working on this btw, I strongly suggest you use the Mod [YUNG'S Better Caves](https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves) as it has all my features plus more and is not broken.

**Comment by kreezxil** [comment]
I've stopped working on this because of Yung's btw, his works so much better.
