### ISSUE TITLE
Subterranean caves still spawn in deep ocean

### ISSUE THREAD

**Issue by Holzwurst123** [kreezxil/Subterranean-Waters#5]
This creates a wierd air bubble underwater:

https://i.imgur.com/Wk8yG67.jpg

Seed: 162755750793055670
(Not sure if reproducable without my modlist, let me know)

This is on latest forge 1.12.2

**Comment by kreezxil** [comment]
why not delete everything form the bug report you feel doesn't apply vs
leaving it all there.

Also, if you think your modlist is to blame why not include it instead of
making me fish for it.

Also none of the recent updates have been for this issue. The last update
was changing the default configs to have a better result when the mod runs
without being configured. IE to experience it delete your current config
and let it regen.

**Comment by Holzwurst123** [comment]
I haven't had this mod before, I only installed the most recent version, so my config is freshly generated, to be safe I did delete it and try again.
EDIT: You don't need my modlist to reproduce, just Subterranean Waters and this seed is enough to reproduce.

**Comment by kreezxil** [comment]
then it's a bad seed as far the mod is concerned. try a different seed. I'll put your seed as a not recommended seed.

**Comment by kreezxil** [comment]
or maybe it's not, also isn't deep ocean another biome type that should be added to the exclusions list?

I think tho, I might've found a solution. Today's update should solve the odd underwater bubbles.

**Comment by kreezxil** [comment]
I think i found why bubbles were occuring in deep ocean, it's because forge sees deep ocean as deep_ocean. testing now.

**Comment by kreezxil** [comment]
today's update contains a very acceptable fix. Using your seed and the update exclusion list in the config I was able to prevent 98% of the bubbling. I found a few odd bubbles but not many enough that it would be acceptable until such time that a coder familiar with biome generation is willing to offer a better solution.

**Comment by Holzwurst123** [comment]
Cool, WDYT about forcing a block update to those upper air blocks, so that if theres water above them, it will flow down.

**Comment by kreezxil** [comment]
From my testing it looks chunks are generated from bottom to the top. So when those air bubbles are formed there are no top blocks to update. I had code in place that checked to see if the block above was water and if so don't generate air but instead water. It didn't work because of the bottom up approach to chunk generation.

Therefore I am not sure how to go about doing as you requested without causing intense world gen lag.

The only thing I can think of us is to implement real air as a block. Air as a gas. And give it the attributes that it must rise. And if water were above air it would want to rise through that.

That will solve the block update but it wont' solve the obvious lag issues that will result.

**Comment by kreezxil** [comment]
We're still working on this btw, I strongly suggest you use the Mod [YUNG'S Better Caves](https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves) as it has all my features plus more and is not broken.
